// mainpage.js — hero slider + recent works (vanilla JS, no jQuery)
// Images loaded from data/site-images.json (generated by: npm run sync)

window.onload = function () {
    fetch('/data/site-images.json')
        .then(function (r) {
            if (!r.ok) throw new Error('HTTP ' + r.status);
            return r.json();
        })
        .then(function (siteData) {
            initSlider(siteData.slider || []);
            initRecentWorks(siteData.recentWorks || []);
        })
        .catch(function () {
            console.error('Could not load /data/site-images.json — run: npm run sync');
        });
};

// ── Hero Scroll-Snap Slider ───────────────────────────────────────────────────

function initSlider(sliderData) {
    var slider      = document.getElementById('heroSlider');
    var dotsNav     = document.getElementById('heroDots');
    var slideCount  = Math.min(8, sliderData.length);
    var current     = 0;
    var dots        = [];
    var scrollTimer = null;
    var autoTimer   = null;

    for (var i = 0; i < slideCount; i++) {
        var slide = document.createElement('div');
        slide.className = 'hero-slide';
        // prefer WebP when available (generated by npm run sync)
        slide.style.backgroundImage = "url('" + (sliderData[i].webp || sliderData[i].image) + "')";
        slide.setAttribute('role', 'img');
        slide.setAttribute('aria-label', sliderData[i].title || ('Slide ' + (i + 1)));
        slider.appendChild(slide);

        var dot = document.createElement('button');
        dot.className = 'hero-dot' + (i === 0 ? ' active' : '');
        dot.setAttribute('aria-label', 'Go to slide ' + (i + 1));
        dotsNav.appendChild(dot);
        dots.push(dot);
    }

    function updateDots() {
        dots.forEach(function (d, i) { d.classList.toggle('active', i === current); });
    }

    function goToSlide(idx) {
        current = ((idx % slideCount) + slideCount) % slideCount;
        slider.scrollTo({ left: current * slider.offsetWidth, behavior: 'smooth' });
        updateDots();
    }

    dots.forEach(function (dot, i) {
        dot.addEventListener('click', function () { resetAutoAdvance(); goToSlide(i); });
    });

    slider.addEventListener('scroll', function () {
        clearTimeout(scrollTimer);
        scrollTimer = setTimeout(function () {
            var idx = Math.round(slider.scrollLeft / slider.offsetWidth);
            if (idx !== current) { current = idx; updateDots(); }
        }, 80);
    }, { passive: true });

    slider.addEventListener('pointerdown', function () { clearInterval(autoTimer); });
    slider.addEventListener('pointerup',   resetAutoAdvance);

    window.addEventListener('resize', function () {
        slider.scrollTo({ left: current * slider.offsetWidth, behavior: 'instant' });
    });

    function resetAutoAdvance() {
        clearInterval(autoTimer);
        autoTimer = setInterval(function () { goToSlide(current + 1); }, 5000);
    }
    resetAutoAdvance();
}

// ── Recent Works ──────────────────────────────────────────────────────────────

function initRecentWorks(recentData) {
    document.querySelectorAll('.portfoliorow').forEach(function (r) {
        r.classList.add('preloader');
    });

    var count = Math.min(6, recentData.length);
    for (var k = 0; k < count; k++) {
        var item = document.getElementById('portfoliorowItem' + k);
        if (!item) continue;
        item.innerHTML = '';

        var photo  = recentData[k];
        var imgSrc = photo.webp || photo.image;

        var img       = document.createElement('img');
        img.src       = imgSrc;
        img.alt       = photo.title || '';
        img.loading   = 'lazy';
        img.className = 'img-responsive img-portfolio img-hover';

        var a       = document.createElement('a');
        a.href      = imgSrc;
        a.title     = photo.title || '';
        a.className = 'image full';
        a.setAttribute('aria-label', photo.title ? 'View photo: ' + photo.title : 'View photo');
        a.appendChild(img);

        var container       = document.createElement('div');
        container.className = 'img-container';
        container.appendChild(a);

        item.appendChild(container);
    }

    // Remove preloader spinner once each image loads
    document.querySelectorAll('.img-portfolio').forEach(function (img) {
        function onLoad() {
            var row = img.closest('.portfoliorow');
            if (row) row.classList.remove('preloader');
        }
        img.addEventListener('load', onLoad, { once: true });
        if (img.complete) onLoad();
    });

    GLightbox({ selector: '.portfolioPhoto a', loop: true, touchNavigation: true });
}
