// portfoliopage.js — portfolio collection viewer (vanilla JS, no jQuery)
// Data from data/site-images.json (generated by: npm run sync)

var _collectionData = {};
var _setLightbox    = null;

// ── Utilities ─────────────────────────────────────────────────────────────────

function show(el) { el.style.display = 'block'; }
function hide(el) { el.style.display = 'none'; }

function fadeIn(el) {
    el.style.opacity = '0';
    show(el);
    requestAnimationFrame(function () {
        requestAnimationFrame(function () { el.style.opacity = '1'; });
    });
}

// ── Set detail view ───────────────────────────────────────────────────────────

function loadSetPage(setNo) {
    hide(document.getElementById('collectionContainer'));
    show(document.querySelector('.setPortfolio-parent'));
    hide(document.getElementById('setFooter'));

    var descEl  = document.getElementById('setDescription');
    var photoEl = document.getElementById('setPhoto');
    descEl.innerHTML  = '';
    photoEl.innerHTML = '';
    photoEl.className = '';
    document.getElementById('setPrimaryPhoto').innerHTML = '';

    location.hash = '#portfolio' + setNo;

    var set = _collectionData.data[setNo];

    // Description
    var h3 = document.createElement('h3');
    h3.textContent = set.title;
    var p = document.createElement('p');
    p.textContent = set.description || '';
    descEl.appendChild(h3);
    descEl.appendChild(p);

    // GLightbox — opens full-size (big) images; prefer WebP when available
    var elements = set.gallery.map(function (photo) {
        return {
            href:        photo.bigWebp  || photo.big,
            type:        'image',
            title:       photo.title       || '',
            description: photo.description || ''
        };
    });
    if (_setLightbox) { _setLightbox.destroy(); _setLightbox = null; }
    _setLightbox = GLightbox({
        elements:           elements,
        loop:               true,
        touchNavigation:    true,
        keyboardNavigation: true
    });

    // CSS-columns photo grid — display medium image (prefer WebP)
    photoEl.className = 'photo-grid';
    set.gallery.forEach(function (photo, idx) {
        var img     = document.createElement('img');
        img.src     = photo.imageWebp || photo.image;
        img.alt     = photo.title || '';
        img.loading = 'lazy';

        var a = document.createElement('a');
        a.href = photo.bigWebp || photo.big;
        a.setAttribute('aria-label', photo.title || ('Photo ' + (idx + 1)));
        a.addEventListener('click', (function (i) {
            return function (e) { e.preventDefault(); _setLightbox.openAt(i); };
        })(idx));
        a.appendChild(img);
        photoEl.appendChild(a);
    });

    // Close button
    var footerEl = document.getElementById('setFooter');
    footerEl.innerHTML = '';

    var btn = document.createElement('button');
    btn.className   = 'btn btn-lg btn-secondary w-100';
    btn.textContent = 'Close';
    btn.addEventListener('click', closeSet);

    var col = document.createElement('div');
    col.className = 'col-md-4 offset-md-4';
    col.appendChild(btn);

    var row = document.createElement('div');
    row.className = 'row';
    row.appendChild(col);

    var well = document.createElement('div');
    well.className = 'well';
    well.appendChild(row);

    footerEl.appendChild(well);
    show(footerEl);
}

function closeSet() {
    if (_setLightbox) { _setLightbox.destroy(); _setLightbox = null; }

    hide(document.querySelector('.setPortfolio-parent'));
    document.getElementById('setPrimaryPhoto').innerHTML = '';
    document.getElementById('setDescription').innerHTML  = '';
    var photoEl = document.getElementById('setPhoto');
    photoEl.innerHTML = '';
    photoEl.className = '';
    document.getElementById('setFooter').innerHTML = '';

    fadeIn(document.getElementById('collectionContainer'));
    location.hash = '';
}

// ── Collection grid ───────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', function () {
    fetch('/data/site-images.json')
        .then(function (r) {
            if (!r.ok) throw new Error('HTTP ' + r.status);
            return r.json();
        })
        .then(function (siteData) {
            _collectionData = siteData.portfolio;
            buildCollectionGrid();
        })
        .catch(function () {
            console.error('Could not load /data/site-images.json — run: npm run sync');
        });
});

function buildCollectionGrid() {
    hide(document.querySelector('.setPortfolio-parent'));

    var container    = document.getElementById('collectionContainer');
    var portfolioRow = document.getElementById('portfoliorow');
    hide(container);
    portfolioRow.innerHTML = '';

    _collectionData.data.forEach(function (set, j) {
        var titleH3 = document.createElement('h3');
        titleH3.textContent = set.title;

        var titleDiv = document.createElement('div');
        titleDiv.className = 'portfolio-title';
        titleDiv.appendChild(titleH3);

        var tile = document.createElement('div');
        tile.id        = 'portfolio_' + j;
        tile.className = 'img-container img-portfolio-div img-hover';
        // prefer WebP cover image when available
        tile.style.background = 'url(' + (set.primary.url_m_webp || set.primary.url_m) + ') no-repeat center center';
        tile.dataset.setIndex  = String(j);
        // Keyboard accessibility (#26): div tiles need explicit role + focus
        tile.setAttribute('role', 'button');
        tile.setAttribute('tabindex', '0');
        tile.setAttribute('aria-label', 'Open ' + set.title + ' gallery');
        tile.appendChild(titleDiv);

        var col = document.createElement('div');
        col.className = 'col-md-4 col-sm-6 portfoliorow';
        col.appendChild(tile);
        portfolioRow.appendChild(col);
    });

    // Single delegated listener for mouse clicks and keyboard activation (#26)
    portfolioRow.addEventListener('click', function (e) {
        var tile = e.target.closest('[data-set-index]');
        if (tile) loadSetPage(parseInt(tile.dataset.setIndex, 10));
    });
    portfolioRow.addEventListener('keydown', function (e) {
        if (e.key !== 'Enter' && e.key !== ' ') return;
        var tile = e.target.closest('[data-set-index]');
        if (tile) { e.preventDefault(); loadSetPage(parseInt(tile.dataset.setIndex, 10)); }
    });

    // Re-open set from URL hash (back-navigation)
    if (location.hash.match(/#portfolio\d+/)) {
        loadSetPage(parseInt(location.hash.match(/\d+/g)[0], 10));
    } else {
        fadeIn(container);
    }
}
