# Site settings
title: RayStudio Photography
header-img: img/home-bg.jpg
email: ray@raystudiophoto.com
description: "A site about photography and few random things."
baseurl: ""
url: "https://raystudiophoto.com"
twitter_username: raystudio
github_username:  raystudioco
facebook_username:  raystudiophoto

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
paginate_path: "/blog/page:num/"
pages_list:       
  #About: '/about'
  Portfolio: '/portfolio'
  Blog: '/blog'
  Contact: '/contact'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude: ["node_modules","package.json","README.md","Gemfile","Gemfile.lock","scripts"]
